apiVersion: v1
kind: Service
metadata:
  name: fulcrum
  namespace: default
  annotations:
    cloud.google.com/network-tier: Standard
spec:
  ports:
    - name: ssl
      port: 50002
      targetPort: 50002
      protocol: TCP
    - name: wss
      port: 50004
      targetPort: 50004
      protocol: TCP
  selector:
    service: fulcrum
  type: LoadBalancer
  # loadBalancerIP: SPECIFIC_LOADBALANCER_IP
  externalTrafficPolicy: Local
