apiVersion: batch/v1
kind: Job
metadata:
  name: fulcrum-certs
spec:
  template:
    metadata:
      name: fulcrum-certs
    spec:
      containers:
      - name: fulcrum-certs
        image: cculianu/fulcrum:v1.9.2
        imagePullPolicy: Always
        command: ["openssl", "req", "-newkey", "rsa:2048", "-sha256", "-nodes", "-x509", "-days", "365", "-subj", "/O=Fulcrum", "-keyout", "/data/fulcrum.key", "-out", "/data/fulcrum.crt"]
        volumeMounts:
          - name: fulcrum-data
            mountPath: /datas
      restartPolicy: Never
      volumes:
        - name: fulcrum-data
          gcePersistentDisk:
            pdName: fulcrum-data
            fsType: ext4
